name: Cypress Tests
on:
  push:
    branches:
    - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cypress
        run: npm install cypress
        
      - name: Install dependencies
        run: npm install

      - name: Cypress run
        run:  npx cypress run

      - name: Navigate and List Files
        run: |
          cd results/junit
          ls


      - name: Merge reports
        run: npm run generateJunitReport

      - name: Sleep
        run: sleep 5

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v3 

        with:
          name: junit-results
          path: automation-report.xml

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress Tests
          path: automation-report.xml
          reporter: jest-junit

    